configured spring boot, created dao,service,entity layers
orest40th/Demo pull request #1
Opened 2024-11-27 14:07 UTC by orest40th

2024-11-27 15:13 UTC, Elena-Bruyako requested changes
see comments

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/model/Book.java
> +@Data
don't use `@Data` for entites, use `@Getter and @Setter `
Also, add `@Table `

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +            throw new RuntimeException("Cannot insert entity into DB: " + book, e);
```suggestion
            throw new DataProcessingException("Cannot insert entity into DB: " + book, e);
```

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +            throw new RuntimeException("Cannot fetch all entities from DB: "
```suggestion
            throw new DataProcessingException("Cannot fetch all books from DB: "
```

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +                    + Book.class.getSimpleName(), e);
```suggestion
                    , e);
```

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-11-27 15:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/service/BookServiceImpl.java
> +    }
```suggestion
```

2024-11-27 15:56 UTC, Elena-Bruyako requested changes

2024-11-27 15:56 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +        try (Session session = sessionFactory.openSession()) {
don't use try with resources and transaction, session will close before catch block

2024-11-27 16:10 UTC, orest40th commented
i also added a tostring method to see what i fetch in my run()

2024-11-28 07:44 UTC, liliia-ponomarenko approved these changes
Good job! 👍

2024-12-07 08:22 UTC, merged