Test
orest40th/Demo pull request #4
Opened 2024-12-07 13:20 UTC by orest40th

2024-12-07 21:13 UTC, Elena-Bruyako requested changes
see comments

2024-12-07 21:13 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
create property for version

2024-12-07 21:13 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>spring-web</artifactId>
```suggestion
			<artifactId>spring-boot-starter-web</artifactId>
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on pom.xml
> +			<version>6.2.0</version>
```suggestion
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
use property

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/DemoApplication.java
> +
```suggestion
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/mapper/BookMapper.java
> +@Mapper(config = com.mate.academy.demo.config.MapperConfig.class)
```suggestion
@Mapper(config = MapperConfig.class)
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/model/Book.java
> +    public String toString() {
remove

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookDaoImpl.java
> +    }
```suggestion
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/repository/BookRepository.java
> +
remove empty line

```suggestion
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/service/BookServiceImpl.java
> +
remove empty line
```suggestion
```

2024-12-07 21:13 UTC, Elena-Bruyako commented on src/main/java/com/mate/academy/demo/service/BookServiceImpl.java
> +                                .collect(Collectors.toList());
```suggestion
                        .map(bookMapper::toDto)
                        .toList();
```

2024-12-07 23:57 UTC, orest40th commented
if i introduce <artifactId>spring-boot-starter-web</artifactId> 
this plugin cannot be found in maven central so i removed it completely

2024-12-17 20:15 UTC, Elena-Bruyako approved these changes

2025-01-26 14:58 UTC, merged